# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UiPathPack@2
  inputs:
    versionType: 'CurrentVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'uipath-zhao'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'uipath-zhao'
    folderName: 'Shared'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'pack_test_case'
    publishLocation: 'Container'

